apiVersion: apps.naeem4265.com/v1
kind: Book
metadata:
  name: book-sample
  labels:
    app.kubernetes.io/name: book
    app.kubernetes.io/instance: book-sample
    app.kubernetes.io/part-of: controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller-kubebuilder
spec:
  container:
    image: naeem4265/api-server:1.0.4
    port: 8080
  deploymentName: "My book"
  replicas: 3
  service:
    name: "book-service"
    servicePort: 8080
