apiVersion: apps.naeem4265.com/v1
kind: Book
metadata:
  name: example-book
spec:
  container:
    image: "naeem4265/api-server:1.0.4"
    port: 8080
  deploymentName: book-deployment
  replicas: 2
  service:
    name: book-service
    servicePort: 8080
