apiVersion: batch.naeem4265.com/v1
kind: Book
metadata:
  labels:
    app.kubernetes.io/name: book
    app.kubernetes.io/instance: book-sample
    app.kubernetes.io/part-of: controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller-kubebuilder
  name: book-sample
spec:
  # TODO(user): Add fields here
